#OHJELMA:
#STEP 1 = PELINALUSTUS
# - PRINT PELIOHJEET
# - PRINT KÄYTTÄJÄLLE OHJEET & KOMENTOVAIHTOEHDOT
# - MÄÄRITÄ SIJAINTI
# - ARVO MARKALAUKUN SIJAINTI
# - ALOITA VIHJE LASKURI
# - ALOITA PÄÄSTÖ LASKURI
# - KYSY NIMI
# - KYSY SEURAAVA MATKUSTUSMAA
# - MATKUSTA

# STEP 2
# - ILMOITA SAAPUMISMAAN TIEDOT
# - PÄIVITÄ SIJAINTI MATKALAUKKUUN
# - ILMOITA PELAAJALLE = Kylmempää/lämpimämpää
# - KM LASKURIN PÄIVITTYMINEN
# - VIHJE LASKURIN PÄIVITTYMINEN
# - KYSY PELAAJALTA UUSI MATKUSTUSMAA




